-- ============================================================
-- Migracion 077: catalogo de sectores empresariales.
--
-- Lote A del plan "Perfil inteligente de empresa" (fusion de UX/
-- funcionalidad de SISSO Demo hacia SISSO Plataforma, Fase 1
-- documentada en AUDITORIA_PARIDAD_DEMO_VS_PLATAFORMA.md).
--
-- La Demo (SISSO-demo-main/index.html) tenia este catalogo
-- hardcodeado en una constante de JavaScript en el navegador
-- (var SECTORES = {...}, 12 sectores). Aqui se convierte en un
-- catalogo real de base de datos, tal como el plan lo exige
-- explicitamente ("NO dejarlos unicamente como datos hardcodeados
-- del frontend"), y se agregan 2 sectores mas ("oficina" y "otro")
-- que el plan pide y que la Demo no tenia.
--
-- DISENO:
--   - Tabla GLOBAL, sin organizacion_id: es un catalogo de
--     referencia compartido por todas las organizaciones, igual
--     que catalogo_cie10 (migration_006) -- que tampoco tiene RLS
--     ni organizacion_id por el mismo motivo: no es un dato de
--     ninguna organizacion en particular, es informacion de
--     referencia que la aplicacion consulta.
--   - Los campos "riesgos" NO incluyen los valores de color/fondo
--     CSS puntuales que traia la Demo (ej. 'var(--red2)'): eso es
--     un detalle de presentacion que pertenece a la capa visual
--     compartida (Fase 7/8 del plan -- "el color del sector debe
--     utilizarse solamente como color de acento, no sustituir la
--     paleta principal SISSO"). El frontend debe mapear el campo
--     "nivel" (alto/medio/bajo) a los tokens de color compartidos,
--     no leer un color hardcodeado desde el catalogo.
--   - "puestos_frecuentes" queda como arreglo vacio en el seed: la
--     Demo no tenia ese dato (aunque el plan lo pide); se deja el
--     campo listo para que el superadmin lo complete via el CRUD
--     de esta misma migracion, en vez de inventar datos que no
--     existian en ninguna fuente real.
--   - Escritura (POST/PUT/DELETE) reservada a superadmin a nivel de
--     aplicacion (ver catalogoSectoresRoutes.js), igual que el
--     patron ya usado para otros catalogos globales editables
--     (ver cargadorCie10.js). No hace falta RLS porque no hay
--     organizacion_id que aislar.
-- ============================================================

CREATE TABLE IF NOT EXISTS catalogo_sectores (
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    clave                       VARCHAR(50) UNIQUE NOT NULL,
    etiqueta                    VARCHAR(150) NOT NULL,
    icono                       VARCHAR(20),
    color_acento                VARCHAR(20),
    color_fondo                 VARCHAR(20),
    descripcion                 TEXT,
    riesgos                     JSONB NOT NULL DEFAULT '[]'::jsonb,
    areas                       JSONB NOT NULL DEFAULT '[]'::jsonb,
    examenes_sugeridos          JSONB NOT NULL DEFAULT '[]'::jsonb,
    herramientas_ergonomicas    JSONB NOT NULL DEFAULT '[]'::jsonb,
    epp_sugerido                JSONB NOT NULL DEFAULT '[]'::jsonb,
    kpis_sugeridos              JSONB NOT NULL DEFAULT '[]'::jsonb,
    puestos_frecuentes          JSONB NOT NULL DEFAULT '[]'::jsonb,
    activo                      BOOLEAN NOT NULL DEFAULT true,
    orden                       INTEGER NOT NULL DEFAULT 0,
    creado_en                   TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_catalogo_sectores_activo ON catalogo_sectores(activo);

-- ------------------------------------------------------------
-- Semilla: 14 sectores (12 migrados desde SISSO Demo + 2 nuevos
-- exigidos por el plan: "oficina" y "otro"). Idempotente: si esta
-- migracion se corre dos veces, no duplica filas.
-- ------------------------------------------------------------
INSERT INTO catalogo_sectores (
    clave, etiqueta, icono, color_acento, color_fondo, descripcion,
    riesgos, areas, examenes_sugeridos,
    herramientas_ergonomicas, epp_sugerido, kpis_sugeridos, puestos_frecuentes, orden
) VALUES
  ('salud', 'Sector Salud', '🏥', '#0d9488', '#ccfbf1', 'Hospitales, clinicas, laboratorios, consultorios, centros de salud',
   '[{"nivel":"alto","icono":"🦠","nombre":"Riesgo biologico","descripcion":"Exposicion a patogenos, fluidos corporales, material contaminado"},{"nivel":"alto","icono":"☢","nombre":"Riesgo quimico","descripcion":"Desinfectantes, anestesicos, citotoxicos, formaldehido"},{"nivel":"alto","icono":"⚡","nombre":"Riesgo ergonomico","descripcion":"Movilizacion de pacientes, bipedestacion prolongada, posiciones forzadas"},{"nivel":"medio","icono":"🧠","nombre":"Riesgo psicosocial","descripcion":"Estres laboral, burnout, carga emocional, turnos nocturnos"},{"nivel":"medio","icono":"🔊","nombre":"Riesgo fisico","descripcion":"Radiaciones ionizantes (Rx), ruido, iluminacion inadecuada"}]'::jsonb, '["Emergencias","UCI / Cuidados intensivos","Quirofano","Laboratorio clinico","Farmacia","Rayos X / Imagenes","Consultorios","Lavanderia","Cocina y nutricion","Administracion"]'::jsonb, '[{"nombre":"Serologia (Hepatitis B, C, VIH)","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Radiografia de torax","tipo":"Obligatorio","frecuencia":"Ingreso + cada 2 anios"},{"nombre":"Prueba tuberculina (PPD)","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Hemograma completo","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Audiometria tonal","tipo":"Segun exposicion","frecuencia":"Ingreso + anual"},{"nombre":"Espirometria","tipo":"Segun exposicion","frecuencia":"Ingreso + anual"},{"nombre":"Evaluacion psicologica","tipo":"Recomendado","frecuencia":"Anual"},{"nombre":"Vacunacion (Hepatitis B, Influenza, Tetanos)","tipo":"Obligatorio","frecuencia":"Segun esquema"}]'::jsonb,
   '["REBA (movilizacion pacientes)","RULA (trabajo en quirofano)","Cuestionario Nordico","Evaluacion bipedestacion prolongada","Analisis de carga postural"]'::jsonb, '["Guantes de latex/nitrilo","Mascarilla N95","Bata / Mandil","Gafas protectoras","Calzado antideslizante","Protector facial","Delantal plomado (Rx)"]'::jsonb, '[{"nombre":"Tasa de accidentes biologicos","meta":"< 2 por 100 trab/año"},{"nombre":"Cobertura de vacunacion Hep B","meta":"> 95%"},{"nombre":"Cumplimiento EMO anual","meta":"100%"},{"nombre":"Casos de lumbalgia ocupacional","meta":"< 5%"}]'::jsonb, '[]'::jsonb, 1),
  ('construccion', 'Construccion', '🏗', '#d97706', '#fef3c7', 'Obras civiles, inmobiliaria, infraestructura, mineria, excavaciones',
   '[{"nivel":"alto","icono":"⬆","nombre":"Trabajo en altura","descripcion":"Caidas desde mas de 1.8 m, andamios, escaleras, techos"},{"nivel":"alto","icono":"💥","nombre":"Riesgo mecanico","descripcion":"Maquinaria pesada, herramientas electricas, materiales en suspension"},{"nivel":"alto","icono":"🪨","nombre":"Riesgo ergonomico","descripcion":"Carga manual de peso excesivo, posturas forzadas, vibraciones"},{"nivel":"medio","icono":"🌬","nombre":"Riesgo quimico","descripcion":"Cemento, polvo de silice, pinturas, solventes, asbestos"},{"nivel":"medio","icono":"🔊","nombre":"Ruido y vibraciones","descripcion":"Martillos, compresoras, maquinaria de corte, vibraciones de mano-brazo"},{"nivel":"bajo","icono":"☀","nombre":"Riesgo climatico","descripcion":"Exposicion solar prolongada, calor extremo, lluvia"}]'::jsonb, '["Obra gruesa","Excavaciones","Instalaciones electricas","Instalaciones sanitarias","Acabados y terminaciones","Bodega de materiales","Oficinas de campo","Taller de equipos"]'::jsonb, '[{"nombre":"Audiometria tonal","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Espirometria","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Radiografia de torax (silicosis)","tipo":"Obligatorio","frecuencia":"Ingreso + cada 2 anios"},{"nombre":"Evaluacion osteoarticular","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Examen neurologico (vibraciones)","tipo":"Segun exposicion","frecuencia":"Anual"},{"nombre":"Agudeza visual","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Test de altura (acrofobia)","tipo":"Obligatorio","frecuencia":"Ingreso"},{"nombre":"Evaluacion cardiovascular","tipo":"Recomendado","frecuencia":"Anual mayores 40 anios"}]'::jsonb,
   '["REBA (carga manual)","Ecuacion NIOSH","Cuestionario Nordico","Evaluacion vibraciones (ISO 5349)","Analisis de trabajo en altura"]'::jsonb, '["Casco de seguridad","Arnes de seguridad","Botas con punta de acero","Guantes de cuero","Gafas de seguridad","Tapones auditivos","Mascarilla antipolvo N95","Chaleco reflectivo","Rodilleras"]'::jsonb, '[{"nombre":"Tasa de accidentes graves","meta":"0 (objetivo cero)"},{"nombre":"Uso de EPP en altura","meta":"100%"},{"nombre":"Incidencia de lumbalgia","meta":"< 8%"},{"nombre":"Cobertura audiometria anual","meta":"100%"}]'::jsonb, '[]'::jsonb, 2),
  ('petroleo', 'Petrolera / Gas', '🛢', '#1d4ed8', '#dbeafe', 'Extraccion, refinacion, transporte de hidrocarburos, petroquimica',
   '[{"nivel":"alto","icono":"🔥","nombre":"Riesgo de explosion e incendio","descripcion":"Gases inflamables, liquidos combustibles, zonas ATEX"},{"nivel":"alto","icono":"☣","nombre":"Riesgo quimico severo","descripcion":"Benceno, H2S, hidrocarburos aromaticos, vapores toxicos"},{"nivel":"alto","icono":"🔊","nombre":"Hipoacusia ocupacional","descripcion":"Ruido de compresoras, turbinas, bombas, generadores (>90 dB)"},{"nivel":"alto","icono":"⚡","nombre":"Riesgo electrico","descripcion":"Alta tension, electricidad estatica, areas clasificadas"},{"nivel":"medio","icono":"🌡","nombre":"Estres termico","descripcion":"Calor extremo en campos, trabajos en ambientes confinados"},{"nivel":"medio","icono":"⬆","nombre":"Trabajo en altura y espacios confinados","descripcion":"Plataformas offshore, torres de perforacion, tanques"}]'::jsonb, '["Campo de extraccion","Planta de refinacion","Laboratorio de analisis","Planta de tratamiento","Cuarto de control","Talleres de mantenimiento","Almacenamiento de quimicos","Oficinas administrativas"]'::jsonb, '[{"nombre":"Audiometria tonal","tipo":"Obligatorio","frecuencia":"Ingreso + semestral"},{"nombre":"Espirometria","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Benceno en sangre / orina","tipo":"Obligatorio","frecuencia":"Trimestral exposicion"},{"nombre":"Hemograma completo","tipo":"Obligatorio","frecuencia":"Semestral"},{"nombre":"Pruebas hepaticas (ALT, AST)","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Evaluacion oftalmologica","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Electrocardiograma","tipo":"Obligatorio","frecuencia":"Anual mayores 40 anios"},{"nombre":"Test espacios confinados","tipo":"Obligatorio","frecuencia":"Ingreso"}]'::jsonb,
   '["REBA","Cuestionario Nordico","Evaluacion vibraciones cuerpo entero","Analisis espacios confinados","RULA (sala de control)"]'::jsonb, '["Casco ATEX","Traje ignifugo","Botas antiaceite y antichispa","Detector de H2S personal","Equipo de respiracion autonoma","Guantes quimicos","Gafas hermeticas","Chaleco reflectivo ATEX"]'::jsonb, '[{"nombre":"Exposicion a benceno (PPM)","meta":"< 0.5 ppm TWA"},{"nombre":"Nivel de ruido promedio","meta":"< 85 dB (8h)"},{"nombre":"Incidentes de proceso","meta":"0 (objetivo cero)"},{"nombre":"Audiometrias con deterioro","meta":"< 3% anual"}]'::jsonb, '[]'::jsonb, 3),
  ('electricidad', 'Electricidad / Energia', '⚡', '#7c3aed', '#ede9fe', 'Generacion, transmision, distribucion electrica, energia renovable',
   '[{"nivel":"alto","icono":"⚡","nombre":"Riesgo electrico","descripcion":"Contacto directo/indirecto, arco electrico, alta tension (AT/MT/BT)"},{"nivel":"alto","icono":"⬆","nombre":"Trabajo en altura","descripcion":"Torres de transmision, postes, aerogeneradores"},{"nivel":"medio","icono":"🔊","nombre":"Ruido","descripcion":"Generadores, transformadores, salas de maquinas"},{"nivel":"medio","icono":"📡","nombre":"Campos electromagneticos","descripcion":"CEM en subestaciones, lineas de alta tension"},{"nivel":"bajo","icono":"🌡","nombre":"Estres termico","descripcion":"Trabajo en exteriores, mantenimiento en calor"}]'::jsonb, '["Sala de control / SCADA","Subestaciones electricas","Lineas de transmision","Planta de generacion","Talleres de mantenimiento","Bodegas de equipos","Oficinas tecnicas"]'::jsonb, '[{"nombre":"Evaluacion cardiovascular (ECG)","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Audiometria tonal","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Agudeza visual y colores","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Test de altura (acrofobia)","tipo":"Obligatorio","frecuencia":"Ingreso"},{"nombre":"Evaluacion neurologica","tipo":"Recomendado","frecuencia":"Anual"},{"nombre":"Espirometria","tipo":"Recomendado","frecuencia":"Ingreso + anual"}]'::jsonb,
   '["REBA (mantenimiento en campo)","RULA (sala de control)","Cuestionario Nordico","Evaluacion trabajo en altura"]'::jsonb, '["Guantes dielectricos clase 00-4","Casco dielectrico Clase E","Botas dielectricas","Traje arco electrico (cal/cm2)","Gafas de seguridad UV","Pértiga aislante","Tapones auditivos","Arnes en altura"]'::jsonb, '[{"nombre":"Accidentes electricos","meta":"0 (objetivo cero)"},{"nombre":"Inspecciones EPP dielectrico","meta":"100% mensual"},{"nombre":"Auditorias de lockout/tagout","meta":"100% trimestral"},{"nombre":"Cobertura EMO anual","meta":"100%"}]'::jsonb, '[]'::jsonb, 4),
  ('comunicaciones', 'Comunicaciones / TIC', '📡', '#0891b2', '#cffafe', 'Telecomunicaciones, tecnologia, call center, medios de comunicacion',
   '[{"nivel":"alto","icono":"🧠","nombre":"Riesgo psicosocial","descripcion":"Estres laboral, acoso, carga cognitiva, trabajo bajo presion"},{"nivel":"alto","icono":"🖥","nombre":"Riesgo ergonomico (pantallas)","descripcion":"Sindrome visual, lumbalgia, sindrome del tunel carpiano, cuello de texto"},{"nivel":"medio","icono":"🔊","nombre":"Ruido (call center)","descripcion":"Auriculares a alta intensidad, ruido ambiental de oficinas abiertas"},{"nivel":"bajo","icono":"☢","nombre":"Radiaciones no ionizantes","descripcion":"Antenas, repetidoras, ondas electromagneticas de equipos"}]'::jsonb, '["Call center / Contact center","Data center","Oficinas administrativas","Sala de servidores","Estaciones de transmision","Laboratorio de redes","Atencion al cliente"]'::jsonb, '[{"nombre":"Evaluacion oftalmologica","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Audiometria tonal","tipo":"Obligatorio","frecuencia":"Ingreso + anual (call center)"},{"nombre":"Evaluacion psicologica","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Evaluacion osteoarticular","tipo":"Recomendado","frecuencia":"Anual"},{"nombre":"Visiometria","tipo":"Obligatorio","frecuencia":"Ingreso + anual"}]'::jsonb,
   '["RULA (trabajo con pantallas)","Cuestionario Nordico","Evaluacion puesto VDT (ISO 9241)","CHECK-LIST OSHA para oficinas"]'::jsonb, '["Filtros de pantalla anti-reflejo","Silla ergonomica regulable","Teclado ergonomico","Reposamuñecas","Auriculares con limitador de volumen (85 dB)"]'::jsonb, '[{"nombre":"Incidencia de sindrome visual","meta":"< 10%"},{"nombre":"Casos de lumbalgia","meta":"< 5%"},{"nombre":"Ausentismo por estres","meta":"< 3%"},{"nombre":"Evaluaciones psicologicas","meta":"100% anual"}]'::jsonb, '[]'::jsonb, 5),
  ('legal', 'Ambito Legal / Juridico', '⚖', '#334155', '#f1f5f9', 'Firmas de abogados, notarias, juzgados, fiscalias, ministerios',
   '[{"nivel":"alto","icono":"🧠","nombre":"Riesgo psicosocial","descripcion":"Estres de alto rendimiento, plazos legales, carga emocional en litigios"},{"nivel":"medio","icono":"🖥","nombre":"Riesgo ergonomico","descripcion":"Trabajo prolongado en escritorio, postura sedente, trabajo con pantallas"},{"nivel":"bajo","icono":"🔆","nombre":"Iluminacion deficiente","descripcion":"Lectura intensiva de documentos, fatiga visual"}]'::jsonb, '["Despachos / Oficinas de abogados","Sala de audiencias","Archivo y documentacion","Sala de reuniones","Recepcion","Administracion"]'::jsonb, '[{"nombre":"Evaluacion psicologica","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Evaluacion oftalmologica","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Visiometria","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Evaluacion cardiovascular","tipo":"Recomendado","frecuencia":"Anual mayores 40 anios"},{"nombre":"Hemograma general","tipo":"Recomendado","frecuencia":"Anual"}]'::jsonb,
   '["RULA (trabajo en escritorio)","Cuestionario Nordico","CHECK-LIST OSHA oficinas","Evaluacion puesto VDT"]'::jsonb, '["Silla ergonomica","Reposamuñecas","Filtro de pantalla","Iluminacion adecuada 500 lux"]'::jsonb, '[{"nombre":"Ausentismo por estres","meta":"< 5%"},{"nombre":"Cumplimiento evaluacion psicologica","meta":"100%"},{"nombre":"Casos de sindrome visual","meta":"< 8%"}]'::jsonb, '[]'::jsonb, 6),
  ('manufactura', 'Manufactura / Industria', '🏭', '#dc2626', '#fee2e2', 'Plantas de produccion, ensamblaje, alimentos, textil, metalmecanica',
   '[{"nivel":"alto","icono":"🔊","nombre":"Ruido industrial","descripcion":"Maquinaria de produccion, compresoras, lineas de ensamblaje (>85 dB)"},{"nivel":"alto","icono":"💪","nombre":"Carga fisica y ergonomia","descripcion":"Carga manual de peso, movimientos repetitivos, posturas forzadas"},{"nivel":"alto","icono":"⚙","nombre":"Riesgo mecanico","descripcion":"Atrapamiento en maquinaria, cortes, aplastamientos"},{"nivel":"medio","icono":"🌡","nombre":"Estres termico","descripcion":"Hornos, fundicion, soldadura, areas sin ventilacion"},{"nivel":"medio","icono":"☁","nombre":"Material particulado","descripcion":"Polvo de madera, metal, quimicos en proceso"}]'::jsonb, '["Linea de produccion","Almacen de materias primas","Almacen de producto terminado","Control de calidad","Mantenimiento","Taller de herramientas","Oficinas de planta"]'::jsonb, '[{"nombre":"Audiometria tonal","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Espirometria","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Evaluacion osteoarticular","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Agudeza visual","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Hemograma completo","tipo":"Recomendado","frecuencia":"Anual"},{"nombre":"Rx torax","tipo":"Segun exposicion","frecuencia":"Ingreso + cada 2 anios"}]'::jsonb,
   '["REBA","RULA","Ecuacion NIOSH","Cuestionario Nordico","Evaluacion movimientos repetitivos (OCRA)"]'::jsonb, '["Tapones auditivos / Orejeras","Casco de seguridad","Guantes de trabajo","Botas con punta de acero","Gafas de seguridad","Mascarilla respiratoria","Delantal de trabajo"]'::jsonb, '[{"nombre":"Trabajadores con hipoacusia","meta":"< 2% anual"},{"nombre":"Accidentes en maquinaria","meta":"0 (objetivo cero)"},{"nombre":"Incidencia lumbalgia","meta":"< 6%"},{"nombre":"Exposicion a ruido > 85 dB","meta":"100% con EPP"}]'::jsonb, '[]'::jsonb, 7),
  ('mineria', 'Mineria', '⛏', '#92400e', '#fef3c7', 'Mineria a cielo abierto, mineria subterranea, procesamiento de minerales',
   '[{"nivel":"alto","icono":"🪨","nombre":"Silicosis / Neumoconiosis","descripcion":"Polvo de silice libre cristalina, exposicion cronica"},{"nivel":"alto","icono":"💥","nombre":"Riesgo de explosion","descripcion":"Uso de explosivos, gases confinados, polvo de carbon"},{"nivel":"alto","icono":"🔊","nombre":"Hipoacusia ocupacional","descripcion":"Perforadoras, voladuras, maquinaria pesada (>100 dB)"},{"nivel":"alto","icono":"🌡","nombre":"Estres termico y frio","descripcion":"Mineria subterranea: calor; cielo abierto: exposicion extrema"},{"nivel":"alto","icono":"😨","nombre":"Espacios confinados","descripcion":"Tuneles, socavones, silos, tanques de lixiviacion"}]'::jsonb, '["Galeria / Socavon","Planta concentradora","Patio de chancado","Laboratorio de analisis","Taller mecanico","Maestranza","Polvorin","Oficinas de campo"]'::jsonb, '[{"nombre":"Espirometria (silicosis)","tipo":"Obligatorio","frecuencia":"Ingreso + semestral"},{"nombre":"Audiometria tonal","tipo":"Obligatorio","frecuencia":"Ingreso + semestral"},{"nombre":"Rx torax + TAC pulmonar","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Test de espacios confinados","tipo":"Obligatorio","frecuencia":"Ingreso"},{"nombre":"Evaluacion cardiovascular","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Hemograma + plomo en sangre","tipo":"Segun exposicion","frecuencia":"Trimestral"},{"nombre":"Test de altura","tipo":"Obligatorio","frecuencia":"Ingreso"},{"nombre":"Evaluacion neurologica","tipo":"Recomendado","frecuencia":"Anual"}]'::jsonb,
   '["REBA (perforacion)","Cuestionario Nordico","Evaluacion vibraciones cuerpo entero","Ecuacion NIOSH (paleo)","Analisis espacios confinados"]'::jsonb, '["Respirador full-face P100","Casco minero con linterna","Botas con punta de acero y antideslizante","Orejeras NRR 33","Traje Tyvek","Autorescatador (mineria subterranea)","Detector de gases 4 en 1","Arnes de seguridad"]'::jsonb, '[{"nombre":"Casos de silicosis","meta":"0 (objetivo cero)"},{"nombre":"Perdida auditiva anual","meta":"< 1% trabajadores"},{"nombre":"Accidentes fatales","meta":"0 (objetivo cero)"},{"nombre":"Espirometrias con deterioro","meta":"< 2% anual"}]'::jsonb, '[]'::jsonb, 8),
  ('agricultura', 'Agricultura / Agroindustria', '🌾', '#15803d', '#dcfce7', 'Cultivos, cosecha, procesamiento agricola, invernaderos, acuicultura',
   '[{"nivel":"alto","icono":"🧪","nombre":"Plaguicidas y agroquimicos","descripcion":"Exposicion a organofosforados, piretroides, fungicidas, herbicidas"},{"nivel":"alto","icono":"☀","nombre":"Estres termico / solar","descripcion":"Trabajo al aire libre, exposicion UV, golpe de calor"},{"nivel":"alto","icono":"💪","nombre":"Carga fisica","descripcion":"Cosecha manual, acarreo, posturas agachadas prolongadas"},{"nivel":"medio","icono":"🌿","nombre":"Riesgo biologico","descripcion":"Hongos, bacterias del suelo, picaduras de insectos, zoonosis"},{"nivel":"medio","icono":"🚜","nombre":"Riesgo mecanico","descripcion":"Maquinaria agricola, tractores, cosechadoras"}]'::jsonb, '["Campo de cultivo","Invernadero","Planta de empaque","Camara de frio","Laboratorio agronomico","Bodega de agroquimicos","Taller agricola","Administracion"]'::jsonb, '[{"nombre":"Colinesterasa eritrocitica (plaguicidas)","tipo":"Obligatorio","frecuencia":"Trimestral exposicion"},{"nombre":"Evaluacion dermatologica","tipo":"Obligatorio","frecuencia":"Semestral"},{"nombre":"Evaluacion osteoarticular","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Espirometria","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Rx torax","tipo":"Recomendado","frecuencia":"Ingreso + anual"},{"nombre":"Hemograma completo","tipo":"Obligatorio","frecuencia":"Semestral"}]'::jsonb,
   '["REBA (cosecha)","Ecuacion NIOSH","Cuestionario Nordico","Evaluacion posturas agachadas (OWAS)"]'::jsonb, '["Traje Tyvek para fumigacion","Respirador quimico OV/P100","Guantes quimicos","Botas de hule","Sombrero de ala ancha","Gafas hermeticas","Protector solar FPS 50+"]'::jsonb, '[{"nombre":"Intoxicaciones por plaguicidas","meta":"0 casos"},{"nombre":"Colinesterasa dentro de norma","meta":"100% trabajadores"},{"nombre":"Casos de golpe de calor","meta":"0 casos"},{"nombre":"Cumplimiento EPP en fumigacion","meta":"100%"}]'::jsonb, '[]'::jsonb, 9),
  ('transporte', 'Transporte / Logistica', '🚛', '#0369a1', '#e0f2fe', 'Transporte de carga y pasajeros, logistica, almacenaje, courier',
   '[{"nivel":"alto","icono":"🚗","nombre":"Accidentes de transito","descripcion":"Conduccion de vehiculos pesados, fatiga al volante, condiciones viales"},{"nivel":"alto","icono":"💺","nombre":"Vibraciones cuerpo entero","descripcion":"Conduccion prolongada, superficies irregulares, choques"},{"nivel":"alto","icono":"🧠","nombre":"Fatiga y somnolencia","descripcion":"Turnos nocturnos, horarios extendidos, jet lag laboral"},{"nivel":"medio","icono":"💪","nombre":"Carga y descarga manual","descripcion":"Manipulacion de bultos, paquetes, pallets"},{"nivel":"medio","icono":"☁","nombre":"Contaminantes vehiculares","descripcion":"Gases de escape diesel, monoxido de carbono, particulas"}]'::jsonb, '["Flota vehicular","Centro de distribucion","Almacen / Bodega","Taller mecanico","Oficinas de despacho","Plataforma de carga","Zona de maniobras"]'::jsonb, '[{"nombre":"Evaluacion psicofisica para conductores","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Test de fatiga y somnolencia (Epworth)","tipo":"Obligatorio","frecuencia":"Semestral"},{"nombre":"Evaluacion oftalmologica (vision nocturna)","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Evaluacion de columna (vibraciones)","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Dosaje de alcohol y drogas","tipo":"Obligatorio","frecuencia":"Aleatoria + ingreso"},{"nombre":"Audiometria tonal","tipo":"Obligatorio","frecuencia":"Ingreso + anual"}]'::jsonb,
   '["Evaluacion vibraciones cuerpo entero (ISO 2631)","REBA (carga y descarga)","Ecuacion NIOSH","Cuestionario Nordico","Analisis puesto de conductor"]'::jsonb, '["Cinturon de seguridad obligatorio","Chaleco reflectivo","Botas de seguridad","Guantes de trabajo","Fajas lumbares (descarga)"]'::jsonb, '[{"nombre":"Accidentes de transito","meta":"< 1 por 100 conductores/anio"},{"nombre":"Test de somnolencia aprobados","meta":"100%"},{"nombre":"Dosaje alcohol positivo","meta":"0%"},{"nombre":"Incidencia lumbalgia conductores","meta":"< 10%"}]'::jsonb, '[]'::jsonb, 10),
  ('educacion', 'Educacion', '🎓', '#7c3aed', '#ede9fe', 'Colegios, universidades, institutos, academias, guarderias',
   '[{"nivel":"alto","icono":"🧠","nombre":"Riesgo psicosocial","descripcion":"Estres docente, burnout, violencia escolar, carga administrativa"},{"nivel":"alto","icono":"🗣","nombre":"Disfonias y nodulos vocales","descripcion":"Uso excesivo de la voz sin amplificacion, ruido ambiental"},{"nivel":"medio","icono":"🦠","nombre":"Riesgo biologico","descripcion":"Infecciones respiratorias, pediculosis, enterovirus en escolares"},{"nivel":"medio","icono":"🖥","nombre":"Riesgo ergonomico","descripcion":"Escritura en pizarras, bipedestacion, carga de mochilas"}]'::jsonb, '["Aulas de clases","Laboratorios","Biblioteca","Sala de profesores","Patios y areas recreativas","Administracion","Cafeteria","Servicios generales"]'::jsonb, '[{"nombre":"Evaluacion psicologica","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Evaluacion laringoscopica (voz)","tipo":"Obligatorio","frecuencia":"Anual docentes"},{"nombre":"Serologia basica (Hepatitis B)","tipo":"Obligatorio","frecuencia":"Ingreso"},{"nombre":"Examen general de orina","tipo":"Recomendado","frecuencia":"Anual"},{"nombre":"Evaluacion osteoarticular","tipo":"Recomendado","frecuencia":"Anual"}]'::jsonb,
   '["RULA (docentes con pantallas)","Cuestionario Nordico","Evaluacion bipedestacion prolongada","Check-list puesto docente"]'::jsonb, '["Microfono / amplificador de voz","Calzado confortable antifatiga","Silla ergonomica ajustable"]'::jsonb, '[{"nombre":"Incidencia de burnout docente","meta":"< 5%"},{"nombre":"Casos de disfonia ocupacional","meta":"< 3%"},{"nombre":"Evaluaciones psicologicas anuales","meta":"100%"}]'::jsonb, '[]'::jsonb, 11),
  ('alimentaria', 'Industria Alimentaria', '🍽', '#d97706', '#fef3c7', 'Procesamiento de alimentos, restaurantes, catering, frigorificos',
   '[{"nivel":"alto","icono":"🧊","nombre":"Estres termico (frio/calor)","descripcion":"Frigorificos -18°C, cocinas industriales, hornos, autoclaves"},{"nivel":"alto","icono":"💧","nombre":"Superficies humedas y resbaladizas","descripcion":"Caidas y resbalones, areas de lavado, pisos mojados"},{"nivel":"alto","icono":"🔪","nombre":"Riesgo por cortes","descripcion":"Cuchillos, sierras de carne, mandolinas, deshuesadoras"},{"nivel":"medio","icono":"🦠","nombre":"Riesgo biologico (inocuidad)","descripcion":"Contaminacion cruzada, manipulacion de alimentos crudos"},{"nivel":"medio","icono":"🔊","nombre":"Ruido","descripcion":"Maquinaria de procesamiento, lavadoras industriales"}]'::jsonb, '["Linea de produccion","Camara frigorifica","Cocina industrial","Control de calidad / laboratorio","Zona de recepcion de materias primas","Almacen seco","Sala de envasado"]'::jsonb, '[{"nombre":"Examen de manipuladores de alimentos (carnet sanitario)","tipo":"Obligatorio","frecuencia":"Anual"},{"nombre":"Coprocultivo y parasitologia","tipo":"Obligatorio","frecuencia":"Semestral"},{"nombre":"Evaluacion dermatologica","tipo":"Obligatorio","frecuencia":"Semestral"},{"nombre":"Audiometria tonal","tipo":"Obligatorio","frecuencia":"Ingreso + anual"},{"nombre":"Evaluacion osteoarticular (frio)","tipo":"Obligatorio","frecuencia":"Anual"}]'::jsonb,
   '["REBA","Ecuacion NIOSH","Cuestionario Nordico","Evaluacion exposicion al frio (ISO 11079)"]'::jsonb, '["Guantes de acero para cortes","Botas antideslizantes con punta","Mandil impermeable","Gorro y mascarilla","Ropa termica (frigorificos)","Tapones auditivos"]'::jsonb, '[{"nombre":"Accidentes por cortes","meta":"< 2 por anio"},{"nombre":"Caidas por suelo humedo","meta":"0 por anio"},{"nombre":"Carnets sanitarios vigentes","meta":"100%"},{"nombre":"Temperatura corporal frio","meta":"Control mensual"}]'::jsonb, '[]'::jsonb, 12),
  ('oficina', 'Oficina / Servicios', '💼', '#475569', '#f1f5f9', 'Oficinas administrativas, servicios generales, actividades sin exposicion industrial relevante',
   '[{"nivel":"medio","icono":"🖥","nombre":"Riesgo ergonomico","descripcion":"Trabajo sedente prolongado, uso de pantallas de visualizacion de datos"},{"nivel":"bajo","icono":"🧠","nombre":"Riesgo psicosocial","descripcion":"Carga de trabajo, relaciones laborales, organizacion del tiempo"}]'::jsonb, '["Oficinas administrativas","Recepcion","Sala de reuniones","Archivo"]'::jsonb, '[{"nombre":"Evaluacion oftalmologica","tipo":"Recomendado","frecuencia":"Anual"},{"nombre":"Evaluacion osteoarticular","tipo":"Recomendado","frecuencia":"Anual"}]'::jsonb,
   '["RULA (trabajo con pantallas)","Cuestionario Nordico","Check-list puesto VDT"]'::jsonb, '["Silla ergonomica","Filtro de pantalla","Reposamuñecas"]'::jsonb, '[{"nombre":"Casos de sindrome visual","meta":"< 8%"},{"nombre":"Ausentismo por causas ergonomicas","meta":"< 3%"}]'::jsonb, '[]'::jsonb, 13),
  ('otro', 'Otro', '⚙', '#64748b', '#f1f5f9', 'Sector no listado -- perfil generico, sin riesgos ni catalogo sugerido predefinido',
   '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
   '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, 14)
ON CONFLICT (clave) DO NOTHING;

-- ------------------------------------------------------------
-- Trigger para mantener actualizado_en al dia en cada UPDATE
-- (mismo patron simple usado en otras tablas de catalogo editable).
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_actualizar_timestamp_catalogo_sectores()
RETURNS TRIGGER AS $$
BEGIN
  NEW.actualizado_en = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_catalogo_sectores_actualizado_en ON catalogo_sectores;
CREATE TRIGGER trg_catalogo_sectores_actualizado_en
  BEFORE UPDATE ON catalogo_sectores
  FOR EACH ROW EXECUTE FUNCTION fn_actualizar_timestamp_catalogo_sectores();

INSERT INTO schema_migrations (version) VALUES ('077_catalogo_sectores')
ON CONFLICT (version) DO NOTHING;
