-- ============================================================
-- SISSO - Migracion 029: cifrado en reposo del secreto TOTP.
--
-- Corrige el hallazgo CRITICO de la auditoria de seguridad:
-- mfa_secret y mfa_secret_pendiente se guardaban en texto plano
-- (ver comentario original en migration_028_mfa.sql).
--
-- Esta migracion NO cambia el esquema (las columnas siguen siendo
-- TEXT: ahora contienen "iv:tag:datos" en base64 en vez de el
-- secreto TOTP crudo). Se deja como migracion numerada, y no como
-- simple cambio de codigo, para que quede registrado en el
-- historial de la base de datos que a partir de esta fecha el
-- contenido de estas columnas cambia de formato.
--
-- ACCION MANUAL REQUERIDA ANTES DE DESPLEGAR EL BACKEND NUEVO:
-- 1. Generar una clave de 32 bytes:
--      node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
-- 2. Definir esa clave como variable de entorno MFA_ENCRYPTION_KEY
--    en Render (Environment). NUNCA guardarla en la base de datos
--    ni en el repositorio.
-- 3. Desplegar el backend. El codigo (src/utils/crypto.js +
--    authController.js) descifra automaticamente los secretos
--    viejos en texto plano si los encuentra (compatibilidad hacia
--    atras) y cifra cualquier secreto NUEVO que se genere desde
--    ahora. No hace falta re-escribir filas existentes a mano.
-- 4. Opcional pero recomendado: pedir a los usuarios que ya tenian
--    MFA activo que lo desactiven y vuelvan a activarlo una vez,
--    para que su secreto quede cifrado tambien (en vez de esperar
--    a que lo hagan por su cuenta).
-- ============================================================

COMMENT ON COLUMN usuarios.mfa_secret IS 'Secreto TOTP cifrado con AES-256-GCM (formato iv:tag:datos, ver src/utils/crypto.js). Los valores anteriores a la migracion 029 pueden estar en texto plano por compatibilidad hacia atras.';
COMMENT ON COLUMN usuarios.mfa_secret_pendiente IS 'Igual que mfa_secret, pero mientras el usuario esta a mitad del proceso de activacion.';
